deployment:
  tasks:
    # Paths
    - export COMPOSER_BIN=/home/quickerf/composer.phar
    - export REPOPATH=/home/quickerf/laravel_suites_repo/quickerfaster.com
    - export DEPLOYPATH=/home/quickerf/public_html
    - export LOGDIR=/home/quickerf/deploy_logs
    - mkdir -p $LOGDIR
    - export LOGFILE=$LOGDIR/deploy_$(date +"%Y-%m-%d_%H-%M-%S").log

    # Start log
    - /bin/echo "===== Deployment started at $(date) =====" >> $LOGFILE

    # Pull latest changes from GitHub
    - /bin/echo "Pulling latest changes from GitHub..." >> $LOGFILE
    - cd $REPOPATH && /usr/bin/git pull origin main >> $LOGFILE 2>&1

    # Clean destination folder but preserve .env, .cpanel.yml, storage, bootstrap
    - /bin/echo "Cleaning destination folder..." >> $LOGFILE
    - /bin/sh -c 'for f in $(/bin/ls -A "$DEPLOYPATH"); do
        [ "$f" = ".env" ] || [ "$f" = ".cpanel.yml" ] || [ "$f" = "storage" ] || [ "$f" = "bootstrap" ] || /bin/rm -rf "$DEPLOYPATH/$f";
      done' >> $LOGFILE 2>&1

    # Copy repository files to deployment path (EXCEPT public folder)
    - /bin/echo "Copying files to deployment path..." >> $LOGFILE
    - /bin/sh -c 'cd "$REPOPATH" && /bin/cp -a $(/bin/ls -A | grep -vE "^(\.git|\.env|\.cpanel\.yml|public)$") "$DEPLOYPATH"' >> $LOGFILE 2>&1

    # COPY PUBLIC FOLDER CONTENTS SEPARATELY to root
    - /bin/echo "Copying public folder contents..." >> $LOGFILE
    - /bin/sh -c 'cd "$REPOPATH/public" && /bin/cp -a . "$DEPLOYPATH/"' >> $LOGFILE 2>&1

    # Ensure Laravel storage and cache directories exist and are writable
    - /bin/echo "Ensuring Laravel storage and cache folders exist..." >> $LOGFILE
    - /bin/sh -c '/bin/mkdir -p $DEPLOYPATH/storage/framework/cache/data \
                   $DEPLOYPATH/storage/framework/sessions \
                   $DEPLOYPATH/storage/framework/views \
                   $DEPLOYPATH/bootstrap/cache \
                   $DEPLOYPATH/storage/logs' >> $LOGFILE 2>&1

    # Set proper permissions
    - /bin/echo "Setting permissions..." >> $LOGFILE
    - /bin/sh -c 'chmod -R 775 "$DEPLOYPATH/storage" "$DEPLOYPATH/bootstrap/cache"' >> $LOGFILE 2>&1

    # Install Composer locally if missing
    - /bin/echo "Checking Composer..." >> $LOGFILE
    - /bin/sh -c 'if [ ! -f "$COMPOSER_BIN" ]; then
        /bin/echo "Downloading Composer..." >> $LOGFILE &&
        cd /home/quickerf &&
        /usr/bin/curl -sS https://getcomposer.org/installer -o composer-setup.php &&
        php composer-setup.php --quiet &&
        rm composer-setup.php &&
        /bin/echo "Composer installed successfully" >> $LOGFILE;
      fi'

    # Install PHP dependencies without running scripts
    - /bin/echo "Installing PHP dependencies..." >> $LOGFILE
    - /bin/sh -c 'cd "$DEPLOYPATH" && php "$COMPOSER_BIN" install --no-dev --no-scripts --optimize-autoloader --ignore-platform-reqs >> "$LOGFILE" 2>&1'

    # COMPREHENSIVE CACHE CLEARING FOR LIVEWIRE
    - /bin/echo "Clearing all caches for Livewire compatibility..." >> $LOGFILE
    - /bin/sh -c 'cd "$DEPLOYPATH" && php artisan config:clear >> "$LOGFILE" 2>&1'
    - /bin/sh -c 'cd "$DEPLOYPATH" && php artisan cache:clear >> "$LOGFILE" 2>&1'
    - /bin/sh -c 'cd "$DEPLOYPATH" && php artisan view:clear >> "$LOGFILE" 2>&1'
    - /bin/sh -c 'cd "$DEPLOYPATH" && php artisan route:clear >> "$LOGFILE" 2>&1'
    - /bin/sh -c 'cd "$DEPLOYPATH" && php artisan clear-compiled >> "$LOGFILE" 2>&1'

    # Clear Livewire cache specifically
    - /bin/sh -c 'cd "$DEPLOYPATH" && php artisan livewire:discover >> "$LOGFILE" 2>&1'
    - /bin/sh -c 'cd "$DEPLOYPATH" && rm -rf storage/framework/views/* 2>/dev/null || true' >> "$LOGFILE" 2>&1

    # Run package discovery
    - /bin/echo "Running package discovery..." >> $LOGFILE
    - /bin/sh -c 'cd "$DEPLOYPATH" && php artisan package:discover >> "$LOGFILE" 2>&1'

    # Cache config only (skip route and view caching)
    - /bin/echo "Caching configuration..." >> $LOGFILE
    - /bin/sh -c 'cd "$DEPLOYPATH" && php artisan config:cache >> "$LOGFILE" 2>&1'

    # Run migrations
    - /bin/echo "Running migrations..." >> $LOGFILE
    - /bin/sh -c 'cd "$DEPLOYPATH" && php artisan migrate --force >> "$LOGFILE" 2>&1'

    # Seed database
    - /bin/echo "Seeding database..." >> $LOGFILE
    - /bin/sh -c 'cd "$DEPLOYPATH" && php artisan db:seed --force >> "$LOGFILE" 2>&1'

    # Final optimization (without view caching)
    - /bin/echo "Final optimization..." >> $LOGFILE
    - /bin/sh -c 'cd "$DEPLOYPATH" && php artisan optimize >> "$LOGFILE" 2>&1'


    # Test Livewire component registration
    - /bin/echo "Testing Livewire components..." >> $LOGFILE
    - /bin/sh -c 'cd "$DEPLOYPATH" && php artisan livewire:list >> "$LOGFILE" 2>&1'


    # End log
    - /bin/echo "===== Deployment finished at $(date) =====" >> $LOGFILE

    # Rotate logs - keep only last 5
    - /bin/ls -1t $LOGDIR/deploy_*.log | /usr/bin/tail -n +6 | /bin/xargs -r /bin/rm --
